### ISSUE TITLE
Repeated letters in suggestion causes Exception

### ISSUE THREAD

**Issue by pvojnisek** [pvojnisek/wordle-helper#1]
How is it possible to have `P` yellow and gray in the same time?
Todays solution is `CRIMP`
![image](https://user-images.githubusercontent.com/45441/150685036-1a849894-2eba-4a4c-9e1a-94f25537a14f.png)

**Comment by pvojnisek** [comment]
![image](https://user-images.githubusercontent.com/45441/150957181-e0ccf181-5507-4593-bd5c-4661e50a148b.png)
![image](https://user-images.githubusercontent.com/45441/150957231-718ac540-e798-4b74-a168-db04f58515c6.png)

Same letter multiple times `S` causes error in the flow:
```
Suggestion: spaes
  Enter results pattern (b-black, y-yellow, g-green):
  spaes
->gbybb
   Filtering..
Traceback (most recent call last):
  File "/workspaces/worldle-helper/src/solver.py", line 64, in <module>
    main()
  File "/workspaces/worldle-helper/src/solver.py", line 60, in main
    print(f'  {solver}')
  File "/workspaces/worldle-helper/src/solver.py", line 39, in __repr__
    return str(self._wh)
  File "/workspaces/worldle-helper/src/wordle_helper.py", line 17, in __repr__
    sample = np.random.choice(self._words, 10)
  File "mtrand.pyx", line 915, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken
```

Today the solution is SUGAR. So the first `S` is on the right place and no other `S` exists. So this might be an implementation error in the algorithm - specification gap.
